### ISSUE TITLE
Any plans to support later/current factorio?

### ISSUE THREAD

**Issue by lamont** [ncabatoff/promfacto#1]
I love the idea of this, and I'm a prometheus user already. I note that the mod won't run with 0.14.22 (claims it needs 0.12.x), did you have any plans to update this for 14, or wait a month for 15? 

If not, I'd like to take a stab at contributing it. Please let me know if you're still playing/interested in this work. 

Thanks!

**Comment by ncabatoff** [comment]
I've issued a new release that works for Factorio 0.14.   I haven't tested much, just verified that the mods appear to be generating sane output over the course of a few minutes.  Please let me know if you find issues.

**Comment by lamont** [comment]
Works perfectly, thank you very much. I tested it locally with a new game and also used a large save against my containerized headless server. Even installed your dashboard in grafana, everything looks great.
